main: me.Plugins.GemInfusion.InfusionMain
api-version: 1.18
name: GemInfusion
version: 1.0
author: Drefvelin

depend: [MMOItems, MythicLib]

commands:
  geminfusion:
      useage: /<command>
      description: Gem Infusion Command